Repository system-ui/theme-ui, pull requests merged in 2020-12, with the labels that each got.

#1328 fix: add missing `sx` prop to Box
  packages/components/index.d.ts
Labels: bug

#1332 (docs): Use Hooks page instead of useThemeUI
  packages/docs/src/pages/use-theme-ui.mdx
  packages/docs/src/sidebar.mdx
  packages/docs/static/_redirects
Labels: docs

#1182 Fix theme editor output in docs
  packages/docs/src/pages/customize.js
Labels: waiting-for-release

#1122 (components): Render extra Embed props on iframe tag
  CHANGELOG.md
  packages/components/index.d.ts
  packages/components/src/Embed.js
  packages/components/test/__snapshots__/index.js.snap
  packages/components/test/index.js
  packages/docs/src/pages/components/embed.mdx
Labels: enhancement

#817 add display names to components
  packages/components/src/Alert.js
  packages/components/src/AspectImage.js
  packages/components/src/AspectRatio.js
  packages/components/src/Avatar.js
  packages/components/src/Badge.js
  packages/components/src/Box.js
  packages/components/src/Button.js
  packages/components/src/Card.js
  packages/components/src/Checkbox.js
  packages/components/src/Close.js
  packages/components/src/Container.js
  packages/components/src/Divider.js
  packages/components/src/Donut.js
  packages/components/src/Embed.js
  packages/components/src/Field.js
  packages/components/src/Flex.js
  packages/components/src/Grid.js
  packages/components/src/Heading.js
  packages/components/src/IconButton.js
  packages/components/src/Image.js
  packages/components/src/Input.js
  packages/components/src/Label.js
  packages/components/src/Link.js
  packages/components/src/MenuButton.js
  packages/components/src/Message.js
  packages/components/src/NavLink.js
  packages/components/src/Paragraph.js
  packages/components/src/Progress.js
  packages/components/src/Radio.js
  packages/components/src/SVG.js
  packages/components/src/Select.js
  packages/components/src/Slider.js
  packages/components/src/Spinner.js
  packages/components/src/Switch.js
  packages/components/src/Text.js
  packages/components/src/Textarea.js
Labels: enhancement

#1375 (docs): Update badges on docs homepage
  packages/docs/src/pages/home.mdx
Labels: docs

#1374 docs: Add section on vendor prefixes to object styles guide
  packages/docs/src/pages/guides/object-styles.mdx
Labels: docs
