Repository system-ui/theme-ui, pull requests merged in 2021-04, with the labels that each got.

#1623 fix(css): borderTopWidth accepts number
  packages/css/src/types.ts
  packages/css/test/index.ts
Labels: types

#1658 fix(components): Allow styled-system space props on Paragraph
  packages/components/src/Paragraph.js
  packages/components/test/index.js
Labels: enhancement

#1664 Adding `scroll-margin` props
  packages/css/src/index.ts
  packages/css/src/types.ts
  packages/css/test/index.ts
  packages/docs/src/pages/sx-prop.mdx
Labels: patch

#1670 Add new links to Resources page
  packages/docs/src/pages/resources.mdx
Labels: docs

#1669 Add 2 missing CSS column properties to scales
  packages/css/src/index.ts
  packages/docs/src/pages/sx-prop.mdx
Labels: enhancement

#1668 Add 6 border logical color properties to scales
  packages/css/src/index.ts
  packages/docs/src/pages/sx-prop.mdx
Labels: enhancement

#1639 Refactor color objects and expose default colors as a mode
  packages/color-modes/src/index.tsx
  packages/color-modes/test/index.tsx
  packages/css/src/types.ts
  packages/docs/src/pages/color-modes.mdx
  packages/gatsby-plugin-theme-ui/test/provider.js
Labels: enhancement

#1687 Docs: improve Switch component documentation
  packages/docs/src/pages/components/switch.mdx
Labels: documentation
