Repository system-ui/theme-ui, pull requests merged in 2022-01, with the labels that each got.

#2056 css: Make background a theme-aware property
  packages/css/src/index.ts
Labels: patch

#2069 chore(docs): Fix description of Progress component
  packages/docs/src/pages/components/progress.mdx
Labels: documentation

#2067 components: Fix visual collapsing bug with Switch component
  packages/components/src/Switch.js
  packages/components/test/__snapshots__/index.js.snap
Labels: @theme-ui/components

#2057 sidenav: Fix props leaking to DOM on Pagination component
  packages/sidenav/src/index.tsx
Labels: affects-docs

#2079 fix(docs): Update recommendations in Keyframes doc
  packages/docs/src/pages/guides/keyframes.mdx
Labels: documentation

#2087 docs: Document default theme values
  packages/docs/src/pages/theming.mdx
Labels: documentation

#2081 feat(theme-ui): Add sx prop to BaseStyles component
  packages/theme-ui/src/index.ts
  packages/theme-ui/test/__snapshots__/index.tsx.snap
  packages/theme-ui/test/index.tsx
Labels: enhancement

#2085 Set up CodeSandbox CI
  .codesandbox/ci.json
Labels: internal

#2094 docs(jsx): add some more detail to #with-swc section in jsx-pragma docs
  packages/docs/src/pages/guides/jsx-pragma.mdx
Labels: documentation

#2080 feat(custom-properties): Warn in development on invalid theme keys
  packages/custom-properties/src/index.ts
  packages/custom-properties/test/test.js
Labels: enhancement

#1236 feat(docs): Add custom content for sketchy preset demo
  packages/docs/src/components/components.mdx
  packages/docs/src/components/preset.js
  packages/docs/src/components/presets-demo.js
Labels: documentation

#2082 feat(tailwind): Upgrade Tailwind theme conversion for v3.0
  packages/tailwind/package.json
  packages/tailwind/src/index.ts
  packages/tailwind/test/__snapshots__/test.ts.snap
  packages/tailwind/test/fixture.css
  packages/tailwind/test/index.html
  packages/tailwind/test/test.ts
  yarn.lock
Labels: enhancement
